### ISSUE TITLE
Question: properly handle message processing failure

### ISSUE THREAD

**Issue by loris** [TechnologyAdvice/Squiss#26]
General question about Squiss and I guess SQS more generally:
How would you properly handle "business logic" errors ? I mean errors happening at the developer level (not SQS ones) and which are not "temporary" errors where the message should simply kept in queue to be retried (for instance, due to a network timeout error). An example would be a message containing a line from a CSV file, where the message consumer would parse the line and transform it to a JSON object. Let's say, the CSV line does contain an incorrect number of column: I would like consumer to properly fail, attach the error somehow (eg. "Invalid number of columns found") to the message and move the message somewhere (where it won't be retried automatically, it won't make sense since it will fail over and over again) to allow the developer to analyse/fix the error (either fixing the message content or the consumer logic).
Is this something that could be done using message attributes (to attach the error message)? are we allowed to "edit" attributes of an existing message?
Thanks for your heads up

**Comment by TomFrost** [comment]
Hey Loris! There are two good options here:

Traditionally, this sort of thing would be handled with a dead letter queue. In the SQS console, you can configure your main queue to say that if a message is received a certain maximum number of times, it should be pushed into a different queue and deleted from the main one. At my company we allow our messages to be received two times before pushing to the dead-letter. We allow for one retry in case a node fails or we forcibly restart/redeploy, but if we don't successfully delete the message that time (or willfully `.keep()` or `.release()` it), it goes to the dead letter for human review. If we discover an error in our codebase and wish to re-process all messages in the dead-letter after fixing it, we simply configure the dead-letter queue to use the main queue as ITS dead-letter, with a max receive of 1. Then, simply polling the dead-letter re-introduces those messages back to the main queue.

The above solution doesn't allow you to attach an error message; in SQS, all messages are immutable. There would be no way to attach new information without sending an entirely new message. But, it's nice because it catches all the errors that you couldn't possibly anticipate. If you _did_ anticipate the error and want to attach it, your thought of using message attributes sounds like a great idea as long as those attributes aren't core to your application logic and would cause corruption if a message with an error attribute were to be re-processed. What you'd do in that case is send a _new_ message directly into your dead-letter with the error attribute attached (which you can do with either a second instance of Squiss, or by using the AWS SQS client directly-- which is available as a property of the Squiss instance). Then, when you review that queue, you know that any message lacking an error attribute is one that failed without an anticipated error.

Hope this helped! Let me know if that solves your conundrum.

**Comment by loris** [comment]
Hey @TomFrost 
Thanks a lot for the deep and clear response! really appreciate it! Both options are great and have their pros/cons. I do like how you set a the main queue as a dead-letter queue to its dead-letter queue, pretty clever! I will let you know how I end up implementing it, but the first option looks simpler and should be enough for our needs: business logic errors should be quite rare, so we could just check for failed jobs in the dead-letter queues, and look for the error messages in our server logs.
Thanks again.

**Comment by TomFrost** [comment]
Sure thing! Good luck :)
